theme: jekyll-theme-cayman
title: Vitajte na DEMO stránke mojej diplomovej práce
description: Stránka obsahuje linky na stiahnutie súborov, ktoré sú v práci použité (dostupné na neurčito)
future: true
